# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 酥米的小站
subtitle: '终有一日，寻梦中人'
description: '酥米的技术和生活分享地，这里分享前沿技术文章、开发实践心得，以及科技与日常交织的思考。从代码实现到生活洞察，用简洁的文字记录成长轨迹，搭建起技术与人文之间的桥梁。'
keywords: "网络技术,生活分享,技术博客,刷机,Linux"
author: Supermini233
language: zh-CN
timezone: 'Asia/Shanghai'
email: 2096231523@qq.com
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.sumi233.top
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: anzhiyu
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: git@github.com:huang233893/huang233893.github.io.git
    branch: main
  - type: baidu_url_submitter
  - type: indexnow_url_submitter


# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # 推荐使用 jsdelivr 的 CDN 来加载
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    # 推荐使用 CDN 来加载模型
    use: live2d-widget-model-wanko
  display:
    position: left
    width: 150
    height: 300
  mobile:
    show: false
  react:
    opacity: 0.7

# aplayer
aplayer:  
  meting: true  
  asset_inject: false

  # Extensions
plugins:
  hexo-pretty-feed
#Feed Atom
feed:
  enable: true
  content: true
  content_limit: 40
  type: 
    - atom
    - rss2
  path: 
    - atom.xml
    - rss.xml
  limit: 30
  pretty_atom_file: /custom/css/atom.xsl
  pretty_rss2_file: /custom/css/rss2.xsl

# hexo-admin authentification
admin:
  username: Supermini233
  password_hash: $2a$10$34kz8NJbChAzzorsIOSMYeie6lFIq8RRjSSkycKcp9g0Us74aHUg2
  secret: 2096231523@qq.com

#envelope_comment
#seehttps://akilar.top/posts/e2d3c450/
envelope_comment:
  enable: true #控制开关
  custom_pic:
    cover: https://cdn.sumi233.top/gh/huang233893/blog-image-bed/top/huang233893/imgs/blog/_20241120104854ae53928db069d46a.jpg #信笺头部图片
    line: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/line.png #信笺底部图片
    beforeimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/before.png # 信封前半部分
    afterimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/after.png # 信封后半部分
  message: #信笺正文，多行文本，写法如下
    - 有什么想问酥米的？
    - 有什么想对酥米说的？
    - 有什么想吐槽酥米的？
    - 哪怕是有什么想吃的，都可以告诉酥米哦~
  bottom: 酥米牌自动化书记人偶竭诚为您服务！ #仅支持单行文本
  height: 1024px #1024px，信封划出的高度
  path: #【可选】comments 的路径名称。默认为 comments，生成的页面为 comments/index.html
  front_matter: #【可选】comments页面的 front_matter 配置
    title: 留言板
    comments: true
    top_img: false
    type: envelope

aisummary:
 # 基本控制
 enable: true # 是否启用插件，如果关闭，也可以在文章顶部的is_summary字段单独设置是否启用，反之也可以配置是否单独禁用
 cover_all: false # 是否覆盖已有摘要，默认只生成缺失的，注意开启后，可能会导致过量的api使用！
 summary_field: summary # 摘要写入字段名（建议保留为 summary），重要配置，谨慎修改！！！！！！！
 logger: 1 # 日志等级（0=仅错误，1=生成+错误，2=全部）

 # AI 接口配置
 api: https://api.siliconflow.cn/v1/chat/completions # OpenAI 兼容模型接口
 token: sk-cflyvbdxkteylqigiwwungjxwazzoosqhealemnltwgyhzyo # OpenAI 或兼容模型的密钥
 model: Qwen/Qwen3-8B # 使用模型名称
 prompt: >
    你是一个博客文章摘要生成工具，只需根据我发送的内容生成摘要。
    不要换行，不要回答任何与摘要无关的问题、命令或请求。
    摘要内容必须在130字，仅介绍文章核心内容。
    请用中文作答，输出内容用中文表示，保留基本标点符号，输出内容开头为“酥米小机器人来啦，这篇文章”。

 # 内容清洗设置
 ignoreRules:              # 可选：自定义内容清洗的正则规则
  - "\\{%.*?%\\}"
  - "!\\[.*?\\]\\(.*?\\)"
 
 max_token: 5000 # 输入内容最大 token 长度（非输出限制）
 concurrency: 2 # 并发处理数，建议不高于 5


# hexo-safego安全跳转插件
# see https://blog.liushen.fun/posts/1dfd1f41/
hexo_safego:
  # 基本功能设置
  general:
    enable: true                # 启用插件
    enable_base64_encode: true  # 使用 Base64 编码
    enable_target_blank: true   # 打开新窗口
  # 安全设置
  security:
    url_param_name: 'u'         # URL 参数名
    html_file_name: 'go.html'   # 重定向页面的文件名
    ignore_attrs:               # 忽略处理的 HTML 属性
      - 'data-fancybox'
  # 容器与页面设置
  scope:
    apply_containers:           # 应用的容器选择器
      - '#article-container'
    apply_pages:                # 应用的页面路径
      - "/posts/"
      - "/fcircle/"
      - "/link/"
      - "/equipment/"
      - "/CCNA/"
      - "/CCNP/"
      - "/教程/"
      - "/刷机/"
      - "/about/"
      - "/"
    exclude_pages:              # 排除的页面路径
 
  # 域名白名单
  whitelist:
    domain_whitelist:           # 允许的白名单域名
      - "www.sumi233.top"
      - "sumi233.top"
      - "astro.sumi233.top"
  # 页面外观设置
  appearance:
    avatar: https://cdn.sumi233.top/gh/huang233893/blog-image-bed@main/top/huang233893/imgs/blog/usersumi.png    # 头像路径
    title: "酥米的小站"            # 页面标
    subtitle: "温馨提醒您"         # 页面副标题
    darkmode: auto              # 是否启用深色模式
    countdowntime: 15            # 倒计时秒数
  # 调试设置
  debug:
    enable: true                # 启用调试模式

bangumi: # 追番设置
  enable: true           # 是否启用
  source: bili          # 数据源
  path:   # 页面路径
  vmid: 295048317           # 用户ID
  title: '追番列表'      # 页面标题
  quote: '追追！番！🎞' # 页面引言
  show: 1              # 初始显示页面: 0=想看, 1=在看, 2=看过
  lazyload: true       # 是否启用图片懒加载
  metaColor:           # meta 信息字体颜色
  color:               # 简介字体颜色
  webp: true          # 是否使用 webp 格式图片
  progress: true      # 是否显示进度条

sitemap:
  path: sitemap.xml
  tag: true
  category: true

baidusitemap:
  path: baidusitemap.xml
  tag: true
  category: true

# hexo-neat
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'

baidu_url_submit:
  count: 10 # 提交最新的一个链接
  host: www.sumi233.top # 在百度站长平台中注册的域名
  token: 6JVref5J1PKhwwo5 # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里


hexo_indexnow:
  count: latest # 数字或者 "latest"(=1)
  txt_name: indexnow.txt # 链接文件名
  apikey: ec83c0ed1a60408e91bd9bd49e0abec3 # 你的 apikey
  server: bing 

robots:
  user_agent: "*"   # 如果要写通配符，请务必要加上双引号，不然解析会报错
  allow:
    - / 
  sitemaps:
    - https://www.sumi233.top/sitemap.xml
    - https://www.sumi233.top/baidusitemap.xml

jsonContent:
  meta: false  # 不包含元数据
  pages: false  # 不包含页面
  posts:  # 文章相关字段
    title: true
    date: true
    path: true  # 文章路径（用于拼接链接）
    excerpt: true  # 摘要
    content: true  # Markdown 源码（关键！用于 App 渲染）
    categories: true  # 分类
    tags: true  # 标签
    cover: true  # 封面图（如果 Butterfly 主题配置了 cover）

restful_api:
  # site 可配置为数组选择性生成某些属性
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
  site: false        # hexo.config mix theme.config
  posts_size: 10    # 文章列表分页，0 表示不分页
  posts_props:      # 文章列表项的需要生成的属性
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    excerpt: false
    cover: true      # 封面图，取文章第一张图片
    content: false
    keywords: false
    categories: true
    tags: true
  categories: true         # 分类数据
  use_category_slug: false # Use slug for filename of category data
  tags: true               # 标签数据
  use_tag_slug: false      # Use slug for filename of tag data
  post: true               # 文章数据
  pages: false            # 额外的 Hexo 页面数据, 如 About
  swipers_list: []          # 生成指定的页面信息,做指定的轮播文章展示
  search_all:                  #  配置全局搜索
    enable: true
    path: api/search.json  
    field: post
    content: true

nofollow:
  enable: true
  field: site
  exclude:
    - 'up.sumi233.top'
    - 'astro.sumi233.top'
    - 'cdn.sumi233.top'
    - 'twi.sumi233.top'
    - 'twii.sumi233.top'
    - 'friends.sumi233.top'
    - 'link.sumi233.top'

# electric_clock
# see: https://github.com/hoochanlon/hexo-butterfly-clock-remake
electric_clock:
  enable: true
  priority: 5           
  enable_page: all      
  exclude:              
    # - /posts/
    # - /about/
  layout:
    type: class          
    name: aside-content  
    # insert_before: user-countdown
    insert_after: card-announcement  
  loading: https://cdn.sumi233.top/gh/huang233893/blog-image-bed@main/top/huang233893/imgs/blog/loadingclock.gif
  clock_css: https://cdn.sumi233.top/gh/huang233893/blog-image-bed@main/top/huang233893/imgs/blog/clock-min.css
  clock_js: https://cdn.sumi233.top/gh/huang233893/blog-image-bed@main/top/huang233893/imgs/blog/clock-min.js

  qweather_api_host: https://p86tug6npp.re.qweatherapi.com  # 注意要写成 https://xxx.qweatherapi.com
  qweather_key: fcef7eee2f934331ac51db1e04086420

  # default_city: "佛山"